//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// Function1.rc에서 사용되고 있습니다.
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_FUNCTION_1_DIALOG           102
#define IDD_DIALOG_FUNCTION             130
#define IDD_DIALOG_SKETCH               131
#define IDR_MAINFRAME                   135
#define IDB_BITMAP1                     136
#define IDD_DIALOG_CREATE               136
#define IDB_BITMAP2                     137
#define IDB_BITMAP3                     138
#define IDB_BITMAP4                     139
#define IDR_TMP1                        140
#define IDR_TMP2                        141
#define IDR_RC1                         144
#define IDR_A1                          145
#define IDC_BUTTON_OK                   145
#define IDR_A2                          146
#define IDD_DIALOG_CREATE_E             147
#define IDB_BITMAP_CREATE_E             149
#define IDB_BITMAP_HELP_1               151
#define IDB_BITMAP_HELP_2               152
#define IDB_BITMAP_HELP_3               153
#define IDB_BITMAP_HELP_4               154
#define IDD_DIALOG_HELP                 155
#define IDB_PNG_Ago                     158
#define IDB_PNG_Next                    159
#define IDB_BITMAP_NEXT                 162
#define IDB_BITMAP_AGO                  163
#define IDB_BITMAP_HELP_HELPING2        165
#define IDB_BITMAP_HELP_HELPING1        166
#define IDD_DIALOG_TITLE                167
#define IDB_BITMAP_TITLE                168
#define IDB_BITMAP_HIDESHOW_1           174
#define IDB_BITMAP_HIDESHOW_2           175
#define IDB_BITMAP_HIDESHOW_3           176
#define IDB_BITMAP_HIDESHOW_4           177
#define IDB_BITMAP_Load_1               178
#define IDB_BITMAP_Load_2               179
#define IDB_BITMAP_Load_3               180
#define IDB_BITMAP_Load_4               181
#define IDB_BITMAP_Save_1               182
#define IDB_BITMAP_Save_2               183
#define IDB_BITMAP_Save_3               184
#define IDB_BITMAP_Save_4               185
#define IDB_BITMAP_X                    186
#define IDB_BITMAP18                    187
#define IDB_BITMAP_Y                    187
#define IDB_BITMAP_Drawing_1            188
#define IDB_BITMAP_Drawing_2            189
#define IDB_BITMAP_Drawing_3            190
#define IDB_BITMAP8                     191
#define IDB_BITMAP_Drawing_4            191
#define IDB_BITMAP_Drawing_Cancle_1     192
#define IDB_BITMAP_Drawing_Cancle_2     193
#define IDB_BITMAP_Drawing_Cancle_3     194
#define IDB_BITMAP9                     195
#define IDB_BITMAP_Drawing_Cancle_4     195
#define IDB_BITMAP_HELP_HELPING3        196
#define IDB_BITMAP_HELP_HELPING4        197
#define IDB_BITMAP7                     198
#define IDB_BITMAP_HELP_HELPING5        198
#define IDC_TAB_SELECTION               1004
#define IDC_LIST_FUNCTION               1008
#define IDC_EDIT_FUNCTION               1009
#define IDC_EDIT_EXAM                   1009
#define IDC_LIST2                       1011
#define IDC_BUTTON_ADD                  1015
#define IDC_BUTTON_DELETE               1016
#define IDC_BUTTON_ONOFF                1017
#define IDC_BUTTON_CORRECT              1018
#define IDC_BUTTON_OPEN                 1019
#define IDC_RADIO_LINE                  1021
#define IDC_RADIO2                      1022
#define IDC_BUTTON_DRAW                 1023
#define IDC_BUTTON_RESET                1024
#define IDC_BUTTON_ALLONOFF             1025
#define IDC_BUTTON_HIDESHOW             1025
#define IDC_STATIC_VIEW                 1027
#define IDC_BUTTON_MODIFY               1028
#define IDC_CHECK_X9                    1030
#define IDC_RADIO_ELLIPSE               1030
#define IDC_CHECK_X8                    1031
#define IDC_CHECK1                      1031
#define IDC_CHECK_X7                    1032
#define IDC_EDIT_X                      1032
#define IDC_CHECK_X6                    1033
#define IDC_EDIT_Y                      1033
#define IDC_BUTTON_HELP                 1033
#define IDC_CHECK_X5                    1034
#define IDC_EDIT_A                      1034
#define IDC_CHECK_X4                    1035
#define IDC_EDIT_B                      1035
#define IDC_CHECK_X3                    1036
#define IDC_CHECK_X2                    1037
#define IDC_BUTTON_NEXT                 1037
#define IDC_CHECK_X1                    1038
#define IDC_BUTTON_AGO                  1038
#define IDC_CHECK_X0                    1039
#define IDC_STATIC_AGO                  1039
#define IDC_EDIT_X9                     1040
#define IDC_STATIC_NEXT                 1040
#define IDC_EDIT_X8                     1041
#define IDC_BUTTON1                     1041
#define IDC_BUTTON_SAVE                 1041
#define IDC_EDIT_X7                     1042
#define IDC_EDIT_X6                     1043
#define IDC_EDIT_X5                     1044
#define IDC_EDIT_X4                     1045
#define IDC_EDIT_X3                     1046
#define IDC_EDIT_X2                     1047
#define IDC_EDIT_X1                     1048
#define IDC_EDIT_X0                     1049
#define IDC_COMBO_X4                    1050
#define IDC_COMBO_X3                    1051
#define IDC_BUTTON2                     1051
#define IDC_BUTTON_LOAD                 1051
#define IDC_COMBO_X2                    1052
#define IDC_EDIT1                       1052
#define IDC_COMBO_X1                    1053
#define IDC_EDIT2                       1053
#define IDC_STATIC_X                    1054
#define IDC_COMBO_X5                    1055
#define IDC_STATIC_Y                    1055
#define IDC_COMBO_X6                    1056
#define IDC_STATIC_TEXT                 1056
#define IDC_STATIC_TEXT_FUNCTION        1056
#define IDC_COMBO_X7                    1057
#define IDC_STATIC_TEXT_SKETCH          1057
#define IDC_COMBO_X8                    1058
#define IDC_COMBO_X9                    1059

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        199
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1058
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
